---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-operator
    spec:
      serviceAccountName: aws-operator
      containers:
      - name: aws-operator
        image: sleyva97/aws-operator:latest
