/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/srleyva/aws-operator/pkg/apis/sleyva/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudformations implements CloudformationInterface
type FakeCloudformations struct {
	Fake *FakeSleyvaV1alpha1
	ns   string
}

var cloudformationsResource = schema.GroupVersionResource{Group: "sleyva", Version: "v1alpha1", Resource: "cloudformations"}

var cloudformationsKind = schema.GroupVersionKind{Group: "sleyva", Version: "v1alpha1", Kind: "Cloudformation"}

// Get takes name of the cloudformation, and returns the corresponding cloudformation object, and an error if there is any.
func (c *FakeCloudformations) Get(name string, options v1.GetOptions) (result *v1alpha1.Cloudformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cloudformationsResource, c.ns, name), &v1alpha1.Cloudformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cloudformation), err
}

// List takes label and field selectors, and returns the list of Cloudformations that match those selectors.
func (c *FakeCloudformations) List(opts v1.ListOptions) (result *v1alpha1.CloudformationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cloudformationsResource, cloudformationsKind, c.ns, opts), &v1alpha1.CloudformationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CloudformationList{}
	for _, item := range obj.(*v1alpha1.CloudformationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudformations.
func (c *FakeCloudformations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cloudformationsResource, c.ns, opts))

}

// Create takes the representation of a cloudformation and creates it.  Returns the server's representation of the cloudformation, and an error, if there is any.
func (c *FakeCloudformations) Create(cloudformation *v1alpha1.Cloudformation) (result *v1alpha1.Cloudformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cloudformationsResource, c.ns, cloudformation), &v1alpha1.Cloudformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cloudformation), err
}

// Update takes the representation of a cloudformation and updates it. Returns the server's representation of the cloudformation, and an error, if there is any.
func (c *FakeCloudformations) Update(cloudformation *v1alpha1.Cloudformation) (result *v1alpha1.Cloudformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cloudformationsResource, c.ns, cloudformation), &v1alpha1.Cloudformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cloudformation), err
}

// Delete takes name of the cloudformation and deletes it. Returns an error if one occurs.
func (c *FakeCloudformations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cloudformationsResource, c.ns, name), &v1alpha1.Cloudformation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudformations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cloudformationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CloudformationList{})
	return err
}

// Patch applies the patch and returns the patched cloudformation.
func (c *FakeCloudformations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Cloudformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cloudformationsResource, c.ns, name, data, subresources...), &v1alpha1.Cloudformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cloudformation), err
}
