/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	sleyva_v1alpha1 "github.com/srleyva/aws-operator/pkg/apis/sleyva/v1alpha1"
	versioned "github.com/srleyva/aws-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/srleyva/aws-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/srleyva/aws-operator/pkg/client/listers/sleyva/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CloudformationInformer provides access to a shared informer and lister for
// Cloudformations.
type CloudformationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CloudformationLister
}

type cloudformationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCloudformationInformer constructs a new informer for Cloudformation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCloudformationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCloudformationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCloudformationInformer constructs a new informer for Cloudformation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCloudformationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SleyvaV1alpha1().Cloudformations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SleyvaV1alpha1().Cloudformations(namespace).Watch(options)
			},
		},
		&sleyva_v1alpha1.Cloudformation{},
		resyncPeriod,
		indexers,
	)
}

func (f *cloudformationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCloudformationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cloudformationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sleyva_v1alpha1.Cloudformation{}, f.defaultInformer)
}

func (f *cloudformationInformer) Lister() v1alpha1.CloudformationLister {
	return v1alpha1.NewCloudformationLister(f.Informer().GetIndexer())
}
