kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - myproject.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-operator
subjects:
- kind: ServiceAccount
  name: aws-operator
  namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-operator
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-operator
    spec:
      serviceAccountName: aws-operator
      containers:
      - name: aws-operator
        image: sleyva97/aws-operator:latest
